
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://oscarmcm.com" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: The oscarmcm Blag!
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "A simple and dummy blog with a lot if idea by Oscar Cortez (oscarmcm)" # used by search engines

  # Header and footer text
  header_text: >
     <p>Hi folks, this is my new blog, here I try to write some ideas about development, entrepreneurship and my day to day as a software developer.</p>
     <p>I love solving problems using a text editor and a compiler.</p>
  header_text_feature_image: sample_feature_img_2.png
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: true
  email_address: "hi@oscarmcm.com" # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "oscarmcm"
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "oscar_mcm"
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-74474511-1" # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: "oscarmcmblog"
  katex: false # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
permalink:      pretty
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
gems:
  - jekyll-sitemap
  - jekyll-paginate
exclude:
  - Rakefile
  - Gemfile
  - LICENSE

# use for the rake file
post:
  template: _post-template.txt
  extension: markdown
editor: vim
git:
  branch: gh-pages

# use for the jekyll assets pipeline reborn
asset_pipeline:
  bundle: true
  compress: true
  gzip: true
