# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: The oscar_mcm Blog
description: Blogging about my programmer life
meta_description: "oscarmcm.xyz | Blog"

# Details for the RSS feed generator
url:            'http://blog.oscarmcm.xyz'
author:         'Oscar Cortez'
authorTwitter:  'oscar_mcm'

#remember add this without '/' at the final
baseurl: http://oscarmcm.github.io/blog

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

aboutPage: true
permalink: pretty
paginate: 20
paginate_path: 'page:num'

domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'
disqus: true
disqus_shortname: 'oscarmcmblog'


# Markdown library
markdown: kramdown

pygments: true
highlighter: pygments

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post

