name: The oscar_mcm Blog
description: Blogging about my programmer life
meta_description: "oscarmcm.com | Blog"

aboutPage: true

markdown: kramdown
highlighter: pygments

paginate: 20
baseurl: /blog
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-74474511-1'
disqus: true
disqus_shortname: 'oscarmcmblog'


# Details for the RSS feed generator
url:            'http://blog.oscarmcm.com'
author:         'Oscar Cortez'
authorTwitter:  'oscar_mcm'

permalink:      pretty

gems:
  - jekyll-sitemap

exclude:
  - Rakefile
  - Gemfile
  - LICENSE

# use for the rake file
post:
  template: _post-template.txt
  extension: markdown
editor: vim
git:
  branch: gh-pages

# use for the jekyll assets pipeline reborn
asset_pipeline:
  bundle: true
  compress: true
  output_path: assets
  display_path: blog/assets
  gzip: true

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
